$ANSIBLE_VAULT;1.1;AES256
38303664306662643334666530396665303435333961346534616337313039633131356237363933
3030323562346439366439336361623534626638616633320a633566386534383364363639306265
62613962333835313965656364623664623937316163343631633438636431616235343438323662
3064346439616565610a316566356165656131323534336531646133373463646261336636393532
31303564343638306332656437356532646561303839663937346166653230323065323131653530
30396437613437666231313863393937353163663063386630316137626536353561623765303766
61333533626437633162323038323637306534353031336631303437373734366565646561626232
31353963373639353464396436643163353536613462663334393335653865666236303264306437
65343865633965613735376639396231323762303633613837313366393662623836653233373866
61656338336139313666313033393864383934306137666230346236303839643533613062323331
33633261616264313465333638623131633665616238333030643532353036623539653831666434
32653639393066663135626539363561376339323164623337613032636235313931616533333930
6361
